export enum ErrorCodes {
  USER_INPUT_TOO_LONG = "USER_INPUT_TOO_LONG",
  USER_INPUT_TOO_SHORT = "USER_INPUT_TOO_SHORT",
  USER_INPUT_EMPTY = "USER_INPUT_EMPTY",
  USER_INPUT_INVALID_TYPE = "USER_INPUT_INVALID_TYPE",
  AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
  ALREADY_EXIST = "ALREADY_EXIST",
  NOT_EXIST = "NOT_EXIST",
};
